spring.application.name=Educational Quality Project

# MongoDB Configuration
# Cole aqui sua Connection String do MongoDB Atlas:
# Exemplo: mongodb+srv://<user>:<password>@cluster0.abcde.mongodb.net/database?retryWrites=true&w=majority
spring.data.mongodb.uri=mongodb+srv://guilerstudies:pR2GZsb4a1d2unry@cluster0.otbts.mongodb.net/qualidade-de-software?retryWrites=true&w=majority

# Server Configuration
server.port=8080